version: "3.9"

services:
  backend:
    build: ./Server
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env

  frontend:
    build: ./Client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
